### ISSUE TITLE
Typo in readme.md examples

### ISSUE THREAD

**Issue by BioComSoftware** [pharmbio/sciluigi#30]
Hi. I apologize if an 'issue' is not the right place to point this out, but I just wanted to give you a heads up. There's a couple of typos in the readme.md's example scripts. 

===
The function...
    
    MyFooReplacer.out_replaced()

...is called later in the process as "MyFooReplacer.out_bar()" by the line(s):
        
    self.ex("sed 's/foo/{repl}' {in} > {out}".format(
            repl=self.replacement,
            in=self.in_foo().path,
            out=self.out_bar().path))

I fixed it by simply renaming "MyFooReplacer.out_replaced()" to "MyFooReplacer.out_bar()".

===
The sed line is incomplete (missing the final forward slash and 'global' set)...

    self.ex("sed 's/foo/{repl}' {in} > {out}".format(

...should read...

    self.ex("sed 's/foo/{repl}/g' {in} > {out}".format(

===
Finally, in that same sed line the "in" from the format's "{in}" is a keyword, which (on OSX) breaks the compile. I changed it to "in_text" and "out_text" (for consistency)...

        command = "sed 's/foo/{repl}/g' {in_text} > {out_text}".format(
                                                                   repl = self.replacement, 
                                                                   in_text = self.in_foo().path, 
                                                                   out_text=self.out_bar().path 
                                                                   )
        self.ex(command)

Thanks for the great sciluigi extension! I was just getting ready to code something very similar, when my boss found this. Saved me hours and hours!

**Comment by samuell** [comment]
Thanks for the kind words @BioComSoftware , and for the heads up! :) Will have a look, and fix this right away.
