### ISSUE TITLE
Why do task objects seem to run twice?

### ISSUE THREAD

**Issue by BioComSoftware** [pharmbio/sciluigi#38]
Hey, 

So...I've created a task object called MakeLocalInputTarget(sciluigi.Task) .

    class MakeLocalInputTarget(sciluigi.Task):
        path = sciluigi.Parameter() # <file>
        tmp = TMP('directory')
        print 'MakeLocalInputTarget called...' #333

        def create_local(self, path):
            <make file links to tmp.directory>
            return <tmp.directory>

        def out_target(self):
            if isinstance(self.path, (list, tuple)):
                return sciluigi.TargetInfo(self, self.create_local(self.path))

It's working, but always seems to run the out_target (and maybe or maybe not the whole class) twice. 
ALL the task classes seem to do this. I assumed it only did it when a class failed a run, but it seems to do it when it succeeds too (as in this case).

Is this a feature or an 'undocumented feature' (bug ;)
Is this a feature of sciluigi or luigi?

Thanks!
	
	RunSubprocess: ['/usr/local/bin/luigi', '--module', 'Bioproximity.sciluigi_tasks.PipelineTest1.InTargetTest', 'Segment1', '--local-scheduler', '--PATHOUT', '/Users/(snip)/newrun/', '--PATHIN', "['/Users/(snip)/160812_29.mzML', '/Users/(snip)/160812_30.mzML']"]
	RunSubprocess:MakeLocalInputTarget called...
	RunSubprocess:2017-04-13 11:29:19 |     INFO | --------------------------------------------------------------------------------
	RunSubprocess:2017-04-13 11:29:19 |     INFO | SciLuigi: Segment1 Workflow Started (logging to log/workflow_segment1_started_20170413_092919_612649.log)
	RunSubprocess:2017-04-13 11:29:19 |     INFO | --------------------------------------------------------------------------------
	RunSubprocess:2017-04-13 11:29:19,614 - Segment1 - DEBUG - Starting 'Segment1'
	RunSubprocess:/Library/Python/2.7/site-packages/luigi/parameter.py:259: UserWarning: Parameter Segment1(instance_name=sciluigi_workflow, PATHIN=['/Users/mikes/Documents/Eclipseworkspace/Bioproximity/TESTDATA/SmallTestedMZML/160812_29.mzML', '/Users/mikes/Documents/Eclipseworkspace/Bioproximity/TESTDATA/SmallTestedMZML/160812_30.mzML'], PATHOUT=/Users/mikes/Documents/tmp/newrun/) is not of type string.
	RunSubprocess:  warnings.warn("Parameter {0} is not of type string.".format(str(x)))
	RunSubprocess:######## It is a list...
	RunSubprocess:create_local.path = ['/Users/(snip)/160812_29.mzML', '/Users/(snip)/160812_30.mzML']
	RunSubprocess:######## It is a list...
	RunSubprocess:create_local.path = ['/Users/(snip)/160812_29.mzML', '/Users/(snip)/160812_30.mzML']

**Comment by samuell** [comment]
Thanks for reporting!

I think this might be fixed in [Version 0.9.7](https://github.com/pharmbio/sciluigi/releases/tag/0.9.7) (also pushed to PyPI), thanks to PR #51 by @hjweide. Please re-open if the problem remains.
