### ISSUE TITLE
Luigi Contrib Modules where moved

### ISSUE THREAD

**Issue by xaedes** [pharmbio/sciluigi#41]
See this luigi commit:
https://github.com/spotify/luigi/commit/781613e3157622e5063ca891bdd58e2b75a31f06

>   breaking: Remove deprecated contrib redirections (#2181)
>  
>  After this commit the following imports will no longer work
>  
>      import luigi.s3
>      import luigi.postgres
>  
>  Instead use
>  
>      import luigi.contrib.{s3,postgres}>  

Results in following error:
>  Traceback (most recent call last):
>    File "workflow.py", line 2, in <module>
>      import sciluigi as sl
>    File "/usr/local/lib/python3.5/dist-packages/sciluigi/__init__.py", line 11, in <module>
>      from sciluigi import dependencies
>    File "/usr/local/lib/python3.5/dist-packages/sciluigi/dependencies.py", line 7, in <module>
>      from luigi.postgres import PostgresTarget
>  ImportError: No module named 'luigi.postgres'
>

**Comment by samuell** [comment]
Should be fixed with #40 that was now merged.

**Comment by samuell** [comment]
Closing now, please report if any remaining errors!
