### ISSUE TITLE
Task\Workflow: Why are run twice?

### ISSUE THREAD

**Issue by diegocorradini** [pharmbio/sciluigi#60]
Hi,

My workflow is runnig twice, even if all the tasks end correctly.
I have already opened an issue in Luigi forum.
https://github.com/spotify/luigi/issues/2633

However, it seems to be a Sciluigi behavior.

**Comment by samuell** [comment]
Thanks for reporting!

I think this might be fixed in [Version 0.9.7](https://github.com/pharmbio/sciluigi/releases/tag/0.9.7) (also pushed to PyPI), thanks to PR #51 by @hjweide. Please re-open if the problem remains.
