### ISSUE TITLE
broken with changes to logging in Luigi>2.8.0

### ISSUE THREAD

**Issue by dasturge** [pharmbio/sciluigi#61]
changes to logging configuration setup in luigi>2.8.0 have broken compatibility with sciluigi. This breaks the pip install and conda -c conda-forge installations of sciluigi with the latest (incompatible) version of luigi (2.8.3).

I have tested a toy example of a workflow in luigi 2.8.0 with no logging error.

**Comment by samuell** [comment]
Thanks for reporting! Should be fixed now in [Version 0.9.7](https://github.com/pharmbio/sciluigi/releases/tag/0.9.7) (also pushed to PyPI). Please re-open if the problem remains.
