### ISSUE TITLE
luigi six has been removed (support for python 2 dropped)

### ISSUE THREAD

**Issue by gkennos** [pharmbio/sciluigi#66]
see: https://github.com/spotify/luigi/commit/ee3618ce0b9f7967d33cc817ca52f94fb996ab56

This now no longer allows sciluigi to work with the latest luigi.

either: change setup to require version 2.8.13 of luigi, or likewise remove python 2 support.

**Comment by samuell** [comment]
Hi @gkennos , thanks for reporting this! I know I'm answering way late, but planning to have a look at an upgrade over the end of the year.

**Comment by samuell** [comment]
@gkennos This is now fixed in the dev branch. Hoping to get a new release out tomorrow.

**Comment by samuell** [comment]
@gkennos This should be fixed in the latest release, 0.10.1: https://pypi.org/project/sciluigi/0.10.1/

Please report if there are any issues. Again, big thanks for reporting! :+1:
